id = "remix-min-darker"
name = "Remix Min Darker"
version = "0.0.1"
schema_version = 1
authors = ["FernaandoJr"]
description = "Remix Min Darker"
repository = "https://github.com/your-name/my-zed-extension"