id = "remix-min-darker-theme"
name = "Remix Min Darker"
version = "0.0.3"
schema_version = 1
authors = ["FernaandoJr <fernaando.divino@gmail.com>"]
description = "Dark UI theme for Zed with a minimal, high-contrast palette."
repository = "https://github.com/FernaandoJr/remix-min-darker-zed"
